const Types ={
    EMPLOYEESLOADED : 'EMPLOYEESLOADED',
    EMPLOYEEDETAILSVIEW : 'EMPLOYEEDETAILSVIEW',
    EMPLOYEECOLLECTIONVIEW : 'EMPLOYEECOLLECTIONVIEW',
    CHANGEDETAILSVIEWID : "CHANGEDETAILSVIEWID",
    SEARCHDIRECTORY : "SEARCHDIRECTORY"
};

export default Types;